FirstTask
Teaching-projects/SZE-MOSZE-2020-BruteForce pull request #1
Opened 2020-09-18 18:14 UTC by RichardVas

@hegyhati

2020-09-21 17:03 UTC, vizvezetek reviewed
@hegyhati Mi a sorsa a "Add files via upload" feltöltéseknek?

2020-09-21 19:27 UTC, vizvezetek requested changes
Nos. Első és legfőbb probléma hogy "Add files via upload"-ot nem szeretnék meglátni. Ez nem az a feladat.
A kóddal kapcsolatban vannak kisebb-nagyobb problémák:
A fighter osztály csak alap adattagokat és metódusokat tartalmazzon. Maga a játék "szimulációt" szedjétek ki onnan, nem ott kell lennie. 
A Fighter.h-t szedjétek szét Fighter.h-ra és Fighter.cpp-re. A jelenlegi állapotában nem túl elegáns.

2020-09-21 19:27 UTC, vizvezetek commented on Fighter.h
> +	void setHP(int x) { HP = x; }
Setter függvény nélkül oldjuk meg a feladatot.

2020-09-21 19:27 UTC, vizvezetek commented on Fighter.h
> +	}
Egy alap működést megvalósító osztályban ne használjunk cout-ot.

2020-09-21 19:27 UTC, vizvezetek commented on Fighter.h
> +	Fighter(std::string iname, int ihp, int idmg) : name(iname), HP(ihp), DMG(idmg) {}
Egy destruktort még elbírna az osztály.

2020-09-21 19:27 UTC, vizvezetek commented on Fighter.h
> +	}
Ha ez kikerül a classon kívülre, akkor maradhat a cout. Az osztályon belül más alternatívát kell használni.

2020-09-22 06:34 UTC, hegyhati commented
@RichardVas @vizvezetek elsore figyelmeztetes, masodjara reject.

2020-09-22 17:07 UTC, RichardVas commented
@vizvezetek , @hegyhati 
A kért változtatásokat elvégeztük.

2020-09-22 17:13 UTC, vizvezetek approved these changes
@hegyhati Részemről rendben.

2020-09-22 23:38 UTC, merged