Levelup
Teaching-projects/SZE-MOSZE-2020-BruteForce pull request #5
Opened 2020-10-15 21:35 UTC by RichardVas

@oliverosz Elkészült a levelup megvalósítása.

2020-10-22 09:20 UTC, oliverosz requested changes

2020-10-22 09:20 UTC, oliverosz commented on .github/workflows/codec.yml
> +          path: ./performance_warnings.txt
a scriptben `cppcheck_performance.txt` a fájlnév, és nincs külön performance meg style kimenet (nem is kell különszedni)
amúgy az ilyenek miatt érdemes kerülni a nevek duplikálását, pl. megkaphatná a bash script argumentumként, és akkor nem kellene beleírni literálként

2020-10-22 09:20 UTC, oliverosz commented on Fighter.cpp
> +		levelUP(&enemy);
A level annyival nő, amennyivel kell, de a levelUP nem hívódik meg többször, ha több szintet is lép egyszerre

2020-10-22 09:20 UTC, oliverosz commented on Fighter.cpp
> +void Fighter::levelUP(Fighter *unit)
Ez egy tagfüggvény. Miért nem a saját adattagjaival dolgozik a paraméter helyett?

2020-10-22 09:20 UTC, oliverosz commented on Fighter.cpp
> +	(*unit).MaxHP *= 1.1;
A kerekítés hiányzik.

2020-10-22 09:20 UTC, oliverosz commented on Fighter.h
> +	void deal_dmg(Fighter &enemy);
Zavaró, hogy mind a kettő publikus. Így nem egyértelmű, hogy az osztály használójának melyiket kéne használnia.

2020-10-22 09:20 UTC, oliverosz commented on Fighter.h
> +	void levelUP(Fighter *unit);
Ez se legyen publikus.

2020-10-22 09:20 UTC, oliverosz commented on Fighter.h
> +	int getXP() { return exp; }
Ezek meg legyenek `const`ok.

2020-10-22 09:20 UTC, oliverosz commented on Fighter.h
> +	Fighter(std::string iname, double ihp, int idmg) : name(iname), HP(ihp), DMG(idmg),MaxHP(ihp) {}
stringet const refként adunk át paraméterben, hogy ne másolódjon le feleslegesen

2020-10-22 20:42 UTC, RichardVas commented
A problémákat kijavítottam, azonban  gondom akadt a **void take_dmg(Fighter &enemy)**; és a **void deal_dmg (Fighter &enemy)** metódusok priváttá tételével, ugyanis addig nem tudom priváttá állítani őket, amíg az összecsapás ért felelős függvény osztályon kívül van, ha jól tudom. 
Esetleg helyezzem át a **void duel(Fighter attacker, Fighter defender)** függvényt Source.cpp ből, mint az Attackspeed brances feladatban, vagy ezt a már meglévőt módosítsam azokhoz ? @oliverosz

2020-10-22 21:07 UTC, oliverosz commented
> A problémákat kijavítottam, azonban gondom akadt a **void take_dmg(Fighter &enemy)**; és a **void deal_dmg (Fighter &enemy)** metódusok priváttá tételével, ugyanis addig nem tudom priváttá állítani őket, amíg az összecsapás ért felelős függvény osztályon kívül van, ha jól tudom.
> Esetleg helyezzem át a **void duel(Fighter attacker, Fighter defender)** függvényt Source.cpp ből, mint az Attackspeed brances feladatban, vagy ezt a már meglévőt módosítsam azokhoz ? @oliverosz

Azt, amit a deal_dmg csinál, azt kívülről is meg lehet csinálni a take_dmg megfelelő meghívásával (defender.take_dmg(attacker).

A többi javítás rendben van, lehet frissíteni a masterre és feloldani a konfliktusokat.

2020-10-24 19:29 UTC, RichardVas commented
Elkészültem a jelzett hibák javításával és a conflictok feloldásával, valamit frissítettem az új kimeneteket és javítottam a keletkezett elgépeléseket. @oliverosz

2020-10-25 00:39 UTC, oliverosz approved these changes

2020-10-25 00:39 UTC, merged