Jsonparser
Teaching-projects/SZE-MOSZE-2020-BruteForce pull request #6
Opened 2020-10-15 21:36 UTC by RichardVas

@wajzy Elkészült a Jsonparser megvalósítása.

2020-10-20 17:43 UTC, wajzy requested changes
Ezen még finomítani kell egy kicsit.

2020-10-20 17:43 UTC, wajzy commented on Fighter.cpp
>  Fighter Fighter::parseUnit(std::string fname)
Nem a Fighter osztály feladata parzolni a JSON fájlt.

2020-10-20 17:43 UTC, wajzy commented on Jsonparser.cpp
> +			std::string str00 = "";
Ha javasolhatom, próbálj ennél egy fokkal kifejezőbb változóneveket használni.

2020-10-20 17:43 UTC, wajzy commented on Jsonparser.cpp
> +				str0 = line.substr(0, line.find(':') - 1);
A fájlban lehetnek kisebb hibák, elgépelések. Ne alapozz arra, hogy lesz majd benne pl. kettőspont. Legalább néhány, könnyen elkövethető hiba detektálására készítsd fel az elemzőt!

2020-10-20 17:43 UTC, wajzy commented on Jsonparser.cpp
> +				str00 = str0.substr(str0.find('"') + 1, (str0.rfind('"') - str0.find('"')) - 1);
Gyorsabb eltárolni a " helyét, mint 2x meghatározni.

2020-10-20 17:43 UTC, wajzy commented on Jsonparser.cpp
> +std::string Jsonparser:: determine_type(std::string str)
Nem javaslom a string visszatérési értéket, mert lassan lehet vele dolgozni. Inkább definiálnék mondjuk egy enumot három lehetséges értékkel.

2020-10-20 17:43 UTC, wajzy commented on Jsonparser.cpp
> +{
Most ide is bemásoltad majdnem pontosan ugyanazt, amit fentebb leírtál? Ne csinálj ilyet! Ne legyen redundáns a kód!

2020-10-20 17:43 UTC, wajzy commented on Jsonparser.h
> +	static std::string determine_type(std::string str);
Ezt tényleg látnia kell mindenkinek?

2020-10-25 21:38 UTC, RichardVas commented
@wajzy Elkészültem a jelzett hibák kijavításával.

2020-10-28 08:26 UTC, wajzy approved these changes
Szigorúan véve még mindig vannak olyan helyes JSON fájlok, amikre nincs felkészítve a parzered. Viszont látszik, hogy igyekeztél kijavítani minden hibát, és én sem várok el tökéletes elemzőt. Tekintsük ezt a feladatot késznek.

2020-10-28 08:27 UTC, wajzy commented
@RichardVas Akkor most oldd fel az ütközéseket!

2020-10-30 11:10 UTC, RichardVas commented
@wajzy Elkészültem az ütközések feloldásával és frissítettem a várt kimeneteket.

2020-11-02 14:13 UTC, merged

2020-11-02 14:33 UTC, RichardVas commented
@wajzy 

Tisztelt Tanár Úr!

A Jsonparser branch mergelésünk ügyében írok. Pár napja elkészültem a hibát kijavításával és a conflictok feloldásával.
Commentben akartam magának jelezni, hogy részünkről készen állunk a mergelésre, de comment commit helyett mergelésre commitoltam( miután feloldottam a conclicktokat zöldre váltott).
Nem állt szándékomban a háta mögött és az engedélye nélkül mergelni a branchet, véletlenül félre nyomtam. Tévedésemért elnézését kérem.
Kérdésem az volna, hogy mi a teendőm ebben a helyzetben? Esetleg újból át kell menni a Pull Requesten, vagy létezik valamilyen Github módszer erre a szituációra.
Válaszát előre is köszönöm.

2020-11-02 14:34 UTC, RichardVas commented
@wajzy 

Tisztelt Tanár Úr!

Pár napja elkészültem a hibát kijavításával és a conflictok feloldásával.
Commentben akartam magának jelezni, hogy részünkről készen állunk a mergelésre, de comment commit helyett mergelésre commitoltam( miután feloldottam a conclicktokat zöldre váltott).
Nem állt szándékomban a háta mögött és az engedélye nélkül mergelni a branchet, véletlenül félre nyomtam. Tévedésemért elnézését kérem.
Kérdésem az volna, hogy mi a teendőm ebben a helyzetben? Esetleg újból át kell menni a Pull Requesten, vagy létezik valamilyen Github módszer erre a szituációra.
Válaszát előre is köszönöm.

2020-11-03 13:39 UTC, wajzy commented
Semmi gond, maradjon így.

2020-11-04 18:09 UTC, wajzy commented
Kedves Richard! 

Jó lesz ez így.

Üdvözlettel,

Hatwagner F. Miklós

> On 2020. Nov 2., at 15:35, Richard Vas <notifications@github.com> wrote:
> 
> @wajzy
> 
> Tisztelt Tanár Úr!
> 
> Pár napja elkészültem a hibát kijavításával és a conflictok feloldásával.
> Commentben akartam magának jelezni, hogy részünkről készen állunk a mergelésre, de comment commit helyett mergelésre commitoltam( miután feloldottam a conclicktokat zöldre váltott).
> Nem állt szándékomban a háta mögött és az engedélye nélkül mergelni a branchet, véletlenül félre nyomtam. Tévedésemért elnézését kérem.
> Kérdésem az volna, hogy mi a teendőm ebben a helyzetben? Esetleg újból át kell menni a Pull Requesten, vagy létezik valamilyen Github módszer erre a szituációra.
> Válaszát előre is köszönöm.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.